export interface CompletionEntry {
  label: string;
  kind: "variable" | "function" | "method";
  receiver?: "string" | "number" | "array" | "object";
  signature?: string;
  detail: string;
}

const variable = (label: string, detail: string): CompletionEntry => ({
  label,
  kind: "variable",
  detail,
});

const fn = (
  label: string,
  signature: string,
  detail: string,
): CompletionEntry => ({
  label,
  kind: "function",
  signature,
  detail,
});

const method = (
  receiver: CompletionEntry["receiver"],
  label: string,
  signature: string,
  detail: string,
): CompletionEntry => ({ label, kind: "method", receiver, signature, detail });

export const EXPRESSION_COMPLETIONS: CompletionEntry[] = [
  variable("$json", "Данные текущего item"),
  variable("$item", "Текущий item целиком, включая binary"),
  variable("$index", "Индекс текущего item, начиная с нуля"),
  variable("$items", "Все items на входе узла"),
  variable("$node", 'Выходы других узлов: $node["Имя узла"].json'),
  variable("$trigger", "Данные, с которыми запущен сценарий"),
  variable("$run", "Метаданные запуска: id, origin, attempt"),
  variable("$vars", "Переменные сценария"),
  variable("$binary", "Файлы текущего item"),

  fn("$if", "$if(условие, тогда, иначе)", "Тернарный выбор"),
  fn(
    "$default",
    "$default(значение, запасное)",
    "Запасное значение, если пусто",
  ),
  fn("$isEmpty", "$isEmpty(значение)", "Пусто: null, '', [], {}, NaN"),
  fn("$isNotEmpty", "$isNotEmpty(значение)", "Обратное к $isEmpty"),
  fn("$get", "$get(объект, 'a.b.0.c', запасное)", "Безопасный доступ по пути"),
  fn("$len", "$len(значение)", "Длина строки, массива или число ключей"),
  fn("$keys", "$keys(объект)", "Список ключей"),
  fn("$values", "$values(объект)", "Список значений"),
  fn(
    "$toNumber",
    "$toNumber(значение)",
    "Приведение к числу, запятая как разделитель",
  ),
  fn("$toString", "$toString(значение)", "Приведение к строке"),
  fn("$toBoolean", "$toBoolean(значение)", "Приведение к логическому"),
  fn("$parseJson", "$parseJson(строка)", "Разбор JSON из строки"),
  fn("$stringify", "$stringify(значение, отступ?)", "Сериализация в JSON"),
  fn("$upper", "$upper(строка)", "В верхний регистр"),
  fn("$lower", "$lower(строка)", "В нижний регистр"),
  fn("$trim", "$trim(строка)", "Убрать пробелы по краям"),
  fn("$split", "$split(строка, разделитель)", "Разбить строку"),
  fn("$join", "$join(массив, разделитель)", "Склеить массив"),
  fn("$slug", "$slug(строка)", "Привести к виду для URL"),
  fn("$round", "$round(число, знаков?)", "Округление"),
  fn("$floor", "$floor(число)", "Округление вниз"),
  fn("$ceil", "$ceil(число)", "Округление вверх"),
  fn("$abs", "$abs(число)", "Модуль числа"),
  fn("$min", "$min(a, b, …)", "Минимум"),
  fn("$max", "$max(a, b, …)", "Максимум"),
  fn("$sum", "$sum(массив)", "Сумма"),
  fn("$now", "$now()", "Текущий момент в ISO"),
  fn("$today", "$today()", "Сегодняшняя дата YYYY-MM-DD"),
  fn("$date", "$date(значение?)", "Нормализация даты в ISO"),
  fn("$formatDate", "$formatDate(дата, 'DD.MM.YYYY')", "Форматирование даты"),
  fn("$addDays", "$addDays(дата, дней)", "Сдвиг даты на дни"),
  fn("$addHours", "$addHours(дата, часов)", "Сдвиг даты на часы"),
  fn("$diffDays", "$diffDays(дата1, дата2)", "Разница в днях"),
  fn("$encodeUrl", "$encodeUrl(строка)", "Экранирование для URL"),
  fn("$decodeUrl", "$decodeUrl(строка)", "Обратное экранирование"),
  fn("$base64Encode", "$base64Encode(строка)", "Кодирование в base64"),
  fn("$base64Decode", "$base64Decode(строка)", "Декодирование из base64"),

  method("string", "toUpperCase", "()", "В верхний регистр"),
  method("string", "toLowerCase", "()", "В нижний регистр"),
  method("string", "trim", "()", "Убрать пробелы по краям"),
  method("string", "split", "(разделитель, лимит?)", "Разбить на массив"),
  method("string", "slice", "(от, до?)", "Подстрока"),
  method("string", "includes", "(подстрока)", "Содержит ли подстроку"),
  method("string", "startsWith", "(префикс)", "Начинается ли с"),
  method("string", "endsWith", "(суффикс)", "Заканчивается ли на"),
  method("string", "replace", "(что, чем)", "Замена первого вхождения"),
  method("string", "replaceAll", "(что, чем)", "Замена всех вхождений"),
  method("string", "padStart", "(длина, чем?)", "Дополнить слева"),
  method("string", "padEnd", "(длина, чем?)", "Дополнить справа"),
  method("string", "toNumber", "()", "Привести к числу"),
  method("string", "toJson", "()", "Разобрать как JSON"),
  method("string", "length", "", "Длина строки"),

  method("array", "map", "(item => …)", "Преобразовать каждый элемент"),
  method("array", "filter", "(item => условие)", "Оставить подходящие"),
  method("array", "find", "(item => условие)", "Первый подходящий"),
  method("array", "some", "(item => условие)", "Есть ли хоть один"),
  method("array", "every", "(item => условие)", "Все ли подходят"),
  method("array", "reduce", "((acc, item) => …, начальное)", "Свёртка"),
  method("array", "sort", "(сравнение?)", "Сортировка копии"),
  method("array", "sortBy", "('поле')", "Сортировка по полю"),
  method("array", "reverse", "()", "Обратный порядок"),
  method("array", "join", "(разделитель?)", "Склеить в строку"),
  method("array", "slice", "(от, до?)", "Подмассив"),
  method("array", "first", "()", "Первый элемент"),
  method("array", "last", "()", "Последний элемент"),
  method("array", "unique", "()", "Убрать дубликаты"),
  method("array", "compact", "()", "Убрать пустые"),
  method("array", "pluck", "('поле')", "Собрать значения поля"),
  method("array", "sum", "()", "Сумма значений"),
  method("array", "avg", "()", "Среднее"),
  method("array", "min", "()", "Минимум"),
  method("array", "max", "()", "Максимум"),
  method("array", "chunk", "(размер)", "Разбить на группы"),
  method("array", "groupBy", "('поле')", "Сгруппировать по полю"),
  method("array", "flat", "(глубина?)", "Развернуть вложенность"),
  method("array", "length", "", "Число элементов"),

  method("object", "keys", "()", "Ключи"),
  method("object", "values", "()", "Значения"),
  method("object", "entries", "()", "Пары ключ-значение"),
  method("object", "get", "('a.b', запасное?)", "Доступ по пути"),
  method("object", "has", "('a.b')", "Есть ли путь"),
  method("object", "merge", "(объект, …)", "Слияние"),
  method("object", "pick", "('a', 'b')", "Оставить только поля"),
  method("object", "omit", "('a', 'b')", "Убрать поля"),
  method("object", "toJson", "()", "Сериализовать"),

  method("number", "toFixed", "(знаков)", "Строка с фиксированной точностью"),
  method("number", "round", "()", "Округление"),
  method("number", "floor", "()", "Округление вниз"),
  method("number", "ceil", "()", "Округление вверх"),
  method("number", "abs", "()", "Модуль"),
];
